### ISSUE TITLE
集成mongodb

### ISSUE THREAD

**Issue by jonnyquan** [mqingyn/torngas#1]
hi,哥们
能集成个mongodb不？

**Comment by mqingyn** [comment]
嗯，这个可以的，未来必然要增加对nosql的支持~

**Comment by mqingyn** [comment]
经过再三考虑，mongdb的支持可能暂时不会加入，因为mongdb并不是普遍的基础的需求，torngas要做的更多是提供一种通用的，简单的应用层框架~将一些必要的基础功能给予支持。

**Comment by mx472756841** [comment]
Hi，哥们！
有个问题需要咨询下你。
~\torngas\dbdbalchemy.py 是不是只支持MySQL？

**Comment by mqingyn** [comment]
非也，dbalchemy是对sqlalchemy的浅层封装，支持什么db取决于sqlalchemy。
