### ISSUE TITLE
集成异步Mysql库

### ISSUE THREAD

**Issue by master-zhuang** [mqingyn/torngas#5]
Hi，哥们儿
Tornado在作为web框架来使用时，如果没有异步的MySQL库支持，它的单线程异步Socket就失去优势了。退化以后使用线程池来异步也是不得已而为之吧，从效率角度讲有没有考虑集成异步MySQL库？

**Comment by mqingyn** [comment]
优化mysql的重要性要更大些，如果查询超过秒级别了，首先要考虑的是优化数据库，而且基本上只要是读取db的场景都可以通过缓存来优化性能，异步的mysql目前并没有很靠谱的client，所以暂时不打算集成异步mysql。
