### ISSUE TITLE
缓存模块，redis用的是同步库，会不会有影响

### ISSUE THREAD

**Issue by tangzhenquan** [mqingyn/torngas#8]
缓存模块，redis用的是同步库，会不会有影响

**Comment by mqingyn** [comment]
不会的。

**Comment by tangzhenquan** [comment]
是用的线程吗？

**Comment by mqingyn** [comment]
没有使用线程，redis查询一般都很快，在毫秒级，很少有redis成为性能瓶颈的时候，通过合理的timeout设置，并不会对系统性能有什么影响。也不需要使用线程。异步更多的是使用在较长时间或者不确定的长时间阻塞，比如请求api，查询关系数据库等等
